version: '3.7'

services:
  bash_script:
    build:
      context: ../bash
      dockerfile: Dockerfile.bash
    container_name: bash_script_container
    restart: always
    networks:
      - mynetwork

  python_script:
    build:
      context: ../python
      dockerfile: Dockerfile.python
    container_name: python_script_container
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
